name: 'CI-master'

on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  master-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
        ref: 'master'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python --version
        pip --version
        make --version
        make init_ci
    - name: Test with pytest
      run: |
        make test
    - name: Lint with flake8
      run: |
        make flake8
    - name: Clean files
      run: |
        make clean
    - name: Create requirements.txt
      run: |
        make requirements
    - name: Create distribution
      run: |
        make create_distribution
    - name: Archive test report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: test-report
        path: report.html
